export {
  notificationTemplate,
  otpEmailTemplate,
  passwordResetConfirmationTemplate,
  queueEmail,
  securityAlertTemplate,
  sendAttendanceConfirmationEmail,
  sendAdminOtpEmail,
  sendEmail,
  sendLeaveDecisionEmail,
  sendOtpEmail,
  sendPasswordResetConfirmation,
  sendSecurityNotification,
  sendStatusEmail,
  sendSystemNotification,
  sendWelcomeEmail,
  statusEmailTemplate,
  welcomeTemplate,
} from "./mail.service.js";
